const bestSellerData = {
    bestsellers: [
        {
            id: 1,
            brand: "GLINT & GLEAM",
            name: "Grey Leather Trousers",
            price: "$120.00",
            discountPrice: null,
            tags: ["BESTSELLER", "NEW ARRIVAL"],
            colors: ["#F4C2C2", "#000000"],
            images: ["/image1.jpg", "/image2.jpg", "/image3.jpg"],
        },
        {
            id: 2,
            brand: "AURELIA WEAR",
            name: "Embroidered Black Mini Dress",
            price: "$184.00",
            discountPrice: "$164.50",
            tags: ["SALE", "NEW ARRIVAL"],
            colors: ["#000000", "#8B4513"],
            images: ["/dress1.jpg", "/dress2.jpg", "/dress3.jpg"],
        },
        {
            id: 200,
            brand: "AURELIA WEAR",
            name: "Embroidered Black Mini Dress",
            price: "$184.00",
            discountPrice: "$164.50",
            tags: ["SALE", "NEW ARRIVAL"],
            colors: ["#000000", "#8B4513"],
            images: ["/dress1.jpg", "/dress2.jpg", "/dress3.jpg"],
        },
        {
            id: 260,
            brand: "AURELIA WEAR",
            name: "Embroidered Black Mini Dress",
            price: "$184.00",
            discountPrice: "$164.50",
            tags: ["SALE", "NEW ARRIVAL"],
            colors: ["#000000", "#8B4513"],
            images: ["/dress1.jpg", "/dress2.jpg", "/dress3.jpg"],
        },
        {
            id: 290,
            brand: "AURELIA WEAR",
            name: "Embroidered Black Mini Dress",
            price: "$184.00",
            discountPrice: "$164.50",
            tags: ["SALE", "NEW ARRIVAL"],
            colors: ["#000000", "#8B4513"],
            images: ["/dress1.jpg", "/dress2.jpg", "/dress3.jpg"],
        },
        {
            id: 3,
            brand: "BENSON & BELLE",
            name: "Dark Beige Midi Dress",
            price: "$460.00",
            discountPrice: null,
            tags: ["TRENDING"],
            colors: ["#F0E68C", "#006400", "#000000"],
            images: ["/midi1.jpg", "/midi2.jpg", "/midi3.jpg"],
        },
        {
            id: 4,
            brand: "IVY & SILK",
            name: "Black White Inserted Trousers",
            price: "$212.00",
            discountPrice: null,
            tags: ["BESTSELLER", "20% OFF"],
            colors: ["#5C4033", "#800080"],
            images: ["/trousers1.jpg", "/trousers2.jpg", "/trousers3.jpg"],
        },
        {
            id: 5,
            brand: "GLINT & GLEAM",
            name: "Beige Oversized Blazer",
            price: "$320.00",
            discountPrice: "$280.00",
            tags: ["SALE"],
            colors: ["#F5F5DC", "#D2B48C"],
            images: ["/blazer1.jpg", "/blazer2.jpg", "/blazer3.jpg"],
        },
    ],
    bottoms: [
        {
            id: 6,
            brand: "BENSON & BELLE",
            name: "Satin Wide-Leg Pants",
            price: "$150.00",
            discountPrice: "$130.00",
            tags: ["BESTSELLER", "LIMITED"],
            colors: ["#800000", "#C0C0C0"],
            images: ["/bottom1.jpg", "/bottom2.jpg", "/bottom3.jpg"],
        },
        {
            id: 7,
            brand: "AURELIA WEAR",
            name: "Classic Black Tailored Pants",
            price: "$110.00",
            discountPrice: null,
            tags: ["TRENDING"],
            colors: ["#000000"],
            images: ["/bottom4.jpg", "/bottom5.jpg", "/bottom6.jpg"],
        },
        {
            id: 8,
            brand: "GLINT & GLEAM",
            name: "Grey High-Waisted Trousers",
            price: "$170.00",
            discountPrice: "$140.00",
            tags: ["SALE"],
            colors: ["#708090"],
            images: ["/bottom7.jpg", "/bottom8.jpg", "/bottom9.jpg"],
        },
        {
            id: 9,
            brand: "IVY & SILK",
            name: "Brown Corduroy Pants",
            price: "$190.00",
            discountPrice: null,
            tags: ["BESTSELLER"],
            colors: ["#8B4513"],
            images: ["/bottom10.jpg", "/bottom11.jpg", "/bottom12.jpg"],
        },
        {
            id: 10,
            brand: "BENSON & BELLE",
            name: "Linen Wide Pants",
            price: "$135.00",
            discountPrice: "$120.00",
            tags: ["NEW ARRIVAL"],
            colors: ["#FAEBD7"],
            images: ["/bottom13.jpg", "/bottom14.jpg", "/bottom15.jpg"],
        },
    ],
    tops: [
        {
            id: 11,
            brand: "IVY & SILK",
            name: "White Linen Shirt",
            price: "$80.00",
            discountPrice: null,
            tags: ["BESTSELLER"],
            colors: ["#FFFFFF"],
            images: ["/top1.jpg", "/top2.jpg", "/top3.jpg"],
        },
        {
            id: 12,
            brand: "AURELIA WEAR",
            name: "Black Cropped Blouse",
            price: "$75.00",
            discountPrice: "$65.00",
            tags: ["SALE"],
            colors: ["#000000"],
            images: ["/top4.jpg", "/top5.jpg", "/top6.jpg"],
        },
        {
            id: 13,
            brand: "GLINT & GLEAM",
            name: "Pink Satin Camisole",
            price: "$50.00",
            discountPrice: null,
            tags: ["NEW ARRIVAL"],
            colors: ["#FFC0CB"],
            images: ["/top7.jpg", "/top8.jpg", "/top9.jpg"],
        },
        {
            id: 14,
            brand: "BENSON & BELLE",
            name: "Printed Button-Up Shirt",
            price: "$90.00",
            discountPrice: null,
            tags: ["TRENDING"],
            colors: ["#ADD8E6"],
            images: ["/top10.jpg", "/top11.jpg", "/top12.jpg"],
        },
        {
            id: 15,
            brand: "IVY & SILK",
            name: "Beige Oversized Sweater",
            price: "$140.00",
            discountPrice: "$120.00",
            tags: ["SALE"],
            colors: ["#D2B48C"],
            images: ["/top13.jpg", "/top14.jpg", "/top15.jpg"],
        },
    ],
    outerwear: [
        {
            id: 16,
            brand: "BENSON & BELLE",
            name: "Black Wool Coat",
            price: "$350.00",
            discountPrice: "$300.00",
            tags: ["BESTSELLER"],
            colors: ["#000000"],
            images: ["/outer1.jpg", "/outer2.jpg", "/outer3.jpg"],
        },
        {
            id: 17,
            brand: "AURELIA WEAR",
            name: "Camel Trench Coat",
            price: "$400.00",
            discountPrice: "$350.00",
            tags: ["SALE"],
            colors: ["#D2B48C"],
            images: ["/outer4.jpg", "/outer5.jpg", "/outer6.jpg"],
        },
        {
            id: 18,
            brand: "GLINT & GLEAM",
            name: "White Faux Fur Jacket",
            price: "$280.00",
            discountPrice: "$250.00",
            tags: ["NEW ARRIVAL"],
            colors: ["#FFFFFF"],
            images: ["/outer7.jpg", "/outer8.jpg", "/outer9.jpg"],
        },
        {
            id: 19,
            brand: "IVY & SILK",
            name: "Green Puffer Jacket",
            price: "$180.00",
            discountPrice: null,
            tags: ["TRENDING"],
            colors: ["#228B22"],
            images: ["/outer10.jpg", "/outer11.jpg", "/outer12.jpg"],
        },
        {
            id: 20,
            brand: "BENSON & BELLE",
            name: "Navy Peacoat",
            price: "$320.00",
            discountPrice: "$280.00",
            tags: ["LIMITED"],
            colors: ["#000080"],
            images: ["/outer13.jpg", "/outer14.jpg", "/outer15.jpg"],
        },
    ],
};

export default bestSellerData;
