export const cardData = [
    {
        id: 1,
        brand: "GLINT & GLEAM",
        name: "Grey Leather Trousers",
        price: "$120.00",
        discountPrice: null,
        tags: ["BESTSELLER", "NEW ARRIVAL"],
        colors: ["#F4C2C2", "#000000"],
        images: ["/image1.jpg", "/image2.jpg", "/image3.jpg"],
    },
    {
        id: 2,
        brand: "AURELIA WEAR",
        name: "Embroidered Black Mini Dress",
        price: "$184.00",
        discountPrice: "$164.50",
        tags: ["SALE", "NEW ARRIVAL"],
        colors: ["#000000", "#8B4513"],
        images: ["/dress1.jpg", "/dress2.jpg", "/dress3.jpg"],
    },
    {
        id: 200,
        brand: "AURELIA WEAR",
        name: "Embroidered Black Mini Dress",
        price: "$184.00",
        discountPrice: "$164.50",
        tags: ["SALE", "NEW ARRIVAL"],
        colors: ["#000000", "#8B4513"],
        images: ["/dress1.jpg", "/dress2.jpg", "/dress3.jpg"],
    },
    {
        id: 260,
        brand: "AURELIA WEAR",
        name: "Embroidered Black Mini Dress",
        price: "$184.00",
        discountPrice: "$164.50",
        tags: ["SALE", "NEW ARRIVAL"],
        colors: ["#000000", "#8B4513"],
        images: ["/dress1.jpg", "/dress2.jpg", "/dress3.jpg"],
    },
    {
        id: 290,
        brand: "AURELIA WEAR",
        name: "Embroidered Black Mini Dress",
        price: "$184.00",
        discountPrice: "$164.50",
        tags: ["SALE", "NEW ARRIVAL"],
        colors: ["#000000", "#8B4513"],
        images: ["/dress1.jpg", "/dress2.jpg", "/dress3.jpg"],
    },
    {
        id: 3,
        brand: "BENSON & BELLE",
        name: "Dark Beige Midi Dress",
        price: "$460.00",
        discountPrice: null,
        tags: ["TRENDING"],
        colors: ["#F0E68C", "#006400", "#000000"],
        images: ["/midi1.jpg", "/midi2.jpg", "/midi3.jpg"],
    },
    {
        id: 4,
        brand: "IVY & SILK",
        name: "Black White Inserted Trousers",
        price: "$212.00",
        discountPrice: null,
        tags: ["BESTSELLER", "20% OFF"],
        colors: ["#5C4033", "#800080"],
        images: ["/trousers1.jpg", "/trousers2.jpg", "/trousers3.jpg"],
    },
    {
        id: 5,
        brand: "GLINT & GLEAM",
        name: "Beige Oversized Blazer",
        price: "$320.00",
        discountPrice: "$280.00",
        tags: ["SALE"],
        colors: ["#F5F5DC", "#D2B48C"],
        images: ["/blazer1.jpg", "/blazer2.jpg", "/blazer3.jpg"],
    },
]