name: Deploy Next.js to EC2

on:
  push:
    branches:
      - main  # Change if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/e-commerce-frontend

            # Pull latest code
            git reset --hard
            git pull origin main

            # Install dependencies
            npm install

            # Build the project
            npm run build

            # Restart the app with PM2
            pm2 restart nextjs-app || pm2 start npm --name "nextjs-app" -- start

            # Save PM2 process list
            pm2 save
          EOF
